# Generated by Django 5.2.3 on 2025-06-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_desc', models.CharField(max_length=255)),
                ('food_image', models.ImageField(upload_to='deals')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
