# Generated by Django 5.2.3 on 2025-06-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seating_pref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sp_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
