# Generated by Django 5.2.3 on 2025-06-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_booking_seating_pref_alter_booking_sp_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seating_pref',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=255, null=True),
        ),
    ]
